apiVersion: apps/v1
kind: Deployment

metadata:
  name: kubernetes-api
  
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      api: kubernetes-api
  template:
    metadata:
      labels:
        api: kubernetes-api
    spec:
      containers:
      - name: kubernetes-api
        image: geraldobl58/kubernetes-api:v5
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: kubernetes-api
          - secretRef:
              name: kubernetes-api-secrets
        # env:
        #   - name: APP
        #     valueFrom:
        #       configMapKeyRef:
        #         name: kubernetes-api
        #         key: app-name
        #   - name: API_KEY
        #     valueFrom:
        #       secretKeyRef:
        #         name: kubernetes-api-secrets
        #         key: api-key
        ports:
          - containerPort: 3000
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi